# Generated by Django 5.1.5 on 2025-03-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_project_projectcell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcell',
            name='project',
        ),
        migrations.AlterField(
            model_name='task',
            name='start_task_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectCell',
        ),
    ]
