# Generated by Django 5.1.5 on 2025-04-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_stickynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='finish_date',
        ),
    ]
