# Generated by Django 5.1.5 on 2025-04-05 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_remove_task_finish_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickynote',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='stickynote',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('purple', 'Purple')], default='yellow', max_length=10),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='title',
            field=models.CharField(default='Untitled Note', max_length=100),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
