# Generated by Django 5.1.5 on 2025-04-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_stickynote_options_stickynote_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='user',
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='color',
            field=models.CharField(choices=[('#fff9c4', 'Yellow'), ('#c8e6c9', 'Green'), ('#bbdefb', 'Blue'), ('#ffccbc', 'Orange'), ('#d1c4e9', 'Purple'), ('#f8bbd0', 'Pink')], default='#fff9c4', max_length=7),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
