# Generated by Django 5.1.5 on 2025-04-30 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_remove_whiteboardroom_created_by_whiteboard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboard',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_whiteboards', to=settings.AUTH_USER_MODEL),
        ),
    ]
